### ISSUE TITLE
serialize() does not pick all paper elements

### ISSUE THREAD

**Issue by Akash-dvd** [PolymerElements/iron-form#49] opened 2015-08-31 09:57 UTC
iron-form serialize method does not pick all paper elements like paper-radio-group ,paper-dropdown-menu. These elements don't have a name attribute but the core elements do have.

**Comment by notwaldorf** [comment] 2015-09-01 17:24
`paper-radio-buttons` (and toggle buttons) should be fixed as of yesterday. 

It is true that `paper-dropdown-menu` doesn't -- I've opened https://github.com/PolymerElements/paper-dropdown-menu/issues/32 for that (since the issue is with the elements themselves, and not the form)

**Closed by notwaldorf** 2015-09-01 17:24 UTC
