### ISSUE TITLE
serializeForm in 2.0 duplicate values

### ISSUE THREAD

**Issue by Oupsla** [PolymerElements/iron-form#168] opened 2017-03-13 12:55 UTC
### Description
The function serializeForm in 2.0-preview duplicates values from inputs contained in a div

This method was serialize in previous versions
This method is use to get all values contained in inputs contained in the form

### Expected outcome

Single value from each input

### Actual outcome

Array of the same value for inputs contained in a div

### Live Demo

No live Demo

### Steps to reproduce

Create a page with a iron-form (2.0-preview)
Add an input inside a div in the form

In the function, get the iron-form with this.$.checkoutForm (for example) and call serializeForm on it

``` html
<iron-form id="checkoutForm"
     on-iron-form-response="_didReceiveResponse"
     on-iron-form-presubmit="_willSendRequest">

            <form method="post" action="http://localhost:3000/foo">
                    <div>
                          <input type="text" name="accountName">
                    </div>
           </form>
</iron-form>
```
### Browsers Affected
- [x ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Not tested in other browser

**Comment by H3dz** [comment] 2017-05-23 23:58
I have the same issue and reproduced it on Firefox and Edge.

The problem seems to be with the _getSubmittableElements function and the way querySelectorAll is used.

querySelectorAll(*) will return all the elements so there's no need to do another query.

The function can be replaced by this and it will work:
```
      _getSubmittableElements: function() {
        // An element is submittable if it is not disabled, and if it has a
        // 'name' attribute.
        return Polymer.dom(this._form).querySelectorAll("[name]:not([disabled]");
      }
```
This works on Chrome, Firefox and Edge.

@notwaldorf the problem is probably also true for _getValidatableElements

**Comment by H3dz** [comment] 2017-05-26 20:17
Duplicate of #166

**Comment by notwaldorf** [comment] 2017-06-19 20:01
I can no longer reproduce this. I have this code:
```html
<iron-form id="checkoutForm">
    <form method="post" action="http://localhost:3000/foo">
      <div>
        <input type="text" name="accountName">
      </div>
    </form>
    <button onclick="console.log(checkoutForm.serializeForm())">Serialize</button>
  </iron-form>
```

Before I type anything, pressing the button prints `Object {accountName: ""}`, and after I mash on the keyboard, I get `Object {accountName: "adsfasdf"}`. This looks correct on both Chrome and Firefox.

I've also added a test for this in 80142fd

**Closed by notwaldorf** 2017-06-19 20:01 UTC

**Comment by H3dz** [comment] 2017-06-19 21:43
@notwaldorf Works well, thanks for the update.
