### ISSUE TITLE
Post content always [object Object]

### ISSUE THREAD

**Issue by hzmnet** [PolymerElements/iron-form#137] opened 2016-07-04 09:06 UTC
### Expected outcome
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
Cache-Control:no-cache
Connection:keep-alive
Content-Length:15
content-type:application/x-www-form-urlencoded
Cookie:VS=0b6c3808782f3f9cad915fb64646f09fcf9aa171
DNT:1
Host:admin.localhost:1688
Origin:http://admin.localhost:1688
Pragma:no-cache
Referer:http://admin.localhost:1688/creator
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

      <form id="form" is="iron-form" class="form" method="post" action="/web/change_password" vertical layout>
        <div style="">
          XXXXXXX
        </div>

        <div class="form-group" vertical layout>
          <paper-input type="password" name="password" label="New Password" class="form-control" required></paper-input>
          <div class="text-error"></div>
        </div>

        <div class="form-group" vertical layout>
          <paper-input type="password" name="password2" label="Confirm Password" class="form-control" required></paper-input>
          <div id="status" class="text-status"></div>
        </div>
        <div class="form-group">
          <paper-button type="submit" name="button" class="btn btn-primary" on-tap="confirmBtn">Confirm</paper-button>
        </div>
      </form>

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by hzmnet** [comment] 2016-07-04 16:14
any one who can fix this?

**Comment by hzmnet** [comment] 2016-07-04 16:38
_var json = this.serialize();_

      // Native forms can also index elements magically by their name (can't make
      // this up if I tried) so we need to get the correct attributes, not the
      // elements with those names.
      this.request.url = this.getAttribute('action');
      this.request.method = this.getAttribute('method');
      this.request.contentType = this.contentType;
      this.request.withCredentials = this.withCredentials;
      this.request.headers = this.headers;

      if (this.method.toUpperCase() === 'POST') {
        this.request.body = json;
      } else {
        this.request.params = json;
      }

# i found this codes and it should not post as Json

**Comment by notwaldorf** [comment] 2016-07-07 14:52
Closing, as I don't understand from the description what the problem is. Can you provide a jsbin with reproducible code we can take a look at, an then we can reopen this? 

The `iron-form` code you posted is a red herring -- `iron-ajax` will take care of the request, based on the `enctype`, `contentType` and `headers` attributes.

**Closed by notwaldorf** 2016-07-07 14:52 UTC

**Comment by hzmnet** [comment] 2016-07-08 06:38
The Iron-form always post content as Json object!
