### ISSUE TITLE
iron-form validate() does not validate "non-required" elements

### ISSUE THREAD

**Issue by sjgjones** [PolymerElements/iron-form#95] opened 2016-01-08 14:42 UTC
Line #329 of iron-form.html is thus:

 if (el.required && !el.disabled) {

Basically it'll only call the validate routines of custom elements that have their required state set.  What is the reasoning behind this?  There may be optional fields, e.g. a zipcode field or telephone number field that whilst not required should still be validated if something has been entered into them ( non-blank ).

I can enter an invalid zipcode into a field that isn't required and the form passes validation.

Right now, the only thing I can think of is to either intercept the form submit and then iterate through each form field's validate() method or modify the iron-form.html file.

**Comment by notwaldorf** [comment] 2016-01-22 07:41
Duplicate of #48

**Closed by notwaldorf** 2016-01-22 07:41 UTC
Labels: duplicate

**Comment by sjgjones** [comment] 2016-01-22 08:01
Unless I'm missing something #48 refers to not validating when there is no "name" attribute on the field.  I am referring to not having the "required" attribute.  This is not the same thing.  I am saying that unless a field is "required" then the form does not validate it regardless of the field requiring validation or not.  There could be an instance where a field is not required but, if a value is entered, it should be validated.  For example, an optional phone number.  It's not required, but if entered, should adhere to a phone number format.  Please reconsider.

**Comment by notwaldorf** [comment] 2016-01-22 08:37
Oh, I see. Unfortunately, that's not how native forms work (http://jsbin.com/benome/edit?html,output). Only `required` elements are validated by the form, regardless of their `name` attribute.

If you want to do validation on your element but _not+ require it in the form I think you have to do this manually with the element itself. For example, in `paper-input`, you could add the `auto-validate` and `pattern` attributes (and then the input will tell you when you're not entering the right thing), but the form won't care.

**Comment by chandrasekharh** [comment] 2016-05-28 01:39
The example (http://jsbin.com/benome/edit?html,output) given in the link only has a 'required' validation which makes sense. But I guess the question posted above is for more custom validations. The phone number example is a very common scenario. Since polymer element supports more flexible validation model. shouldn't iron-form invoke validate regardless of the required attribute?

**Comment by mercmobily** [comment] 2016-07-09 10:26
The scenario where there is an optional phone number that, _if present_, should be validated is basically impossible to implement cleanly.

The explanation given was:

"Unfortunately, that's not how native forms work"

However, the specs always cover regexp, ranges etc. -- all things that imply the presence of "something". So, the constraint makes sense.

In terms of custom elements, this limitation seems to just introduce a limitation for no reason.

Can you please let us know:

1) How we are meant to implement "optional email address"
2) Why it's against the specs to use a custom polymer validator against a custom element
3) Possibly a fix to this limitation

Thank you...!

**Comment by mercmobily** [comment] 2016-07-09 14:42
Added PR #140
