### ISSUE TITLE
Duplicates input values when items placed into divs inside an iron-form

### ISSUE THREAD

**Issue by MTLcoder** [PolymerElements/iron-form#166] opened 2017-02-24 21:21 UTC
### Description
Hello! I'm currently using the `iron-form` component as my main template form in my web app. When putting input inside divs I see some glitches in the payload the ajax called with.
```
<iron-form>
  <form>
   <div>
    <paper-input name="email"></paper-input>
    <paper-input name="password"></paper-input>
   </div>
   <button type="submit">Submit</button>
  </form>
</iron-form>
```

### Expected outcome
I should get a payload looking like this:
`{email: "emailValue", password: "passwordValue"}`

### Actual outcome
But I get this:
`{email: ["emailValue", "emailValue"], password: ["passwordValue", "passwordValue"]}`

### Steps to reproduce
Just wrap some inputs inside a div, itself inside an `iron-form`.

### Workaround
I replaced in iron-form.html at line 317
`var nodes = Polymer.dom(this._form).querySelectorAll('*');` 
by 
`var nodes = Polymer.dom(this._form).children;`
and it works as expected now.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

Were you aware of this? :)

**Comment by jehna** [comment] 2017-03-01 14:24
Here's a quick-fix you can run from container component:

```
this.$.yourFormComponentsId._getSubmittableElements = function () {
  return Array.prototype.slice.call(Polymer.dom(this._form).querySelectorAll('*'))
    .filter(el => !el.disabled && el.name)
}
```

**Comment by MTLcoder** [comment] 2017-03-02 12:54
Hey @jehna!
Thank you, it works perfectly! 

Have a great day :)

**Comment by notwaldorf** [comment] 2017-06-19 20:02
Duplicate of https://github.com/PolymerElements/iron-form/issues/168. Closed, since I can't repro it anymore

**Closed by notwaldorf** 2017-06-19 20:02 UTC
