### ISSUE TITLE
Hooking into form pre-submission

### ISSUE THREAD

**Issue by zmoshansky** [PolymerElements/iron-form#26] opened 2015-07-10 02:01 UTC
Is it possible to hook into the form flow prior to submission? The use-case would be to modify the json to move the attributes inside an object. 

Now:
```
{"foo": "bar"}
```

Desired:
```
{
  "list": {
    "foo": "bar"
  }
}
```

**Comment by klarkc** [comment] 2015-07-14 19:24
Same problem here, I need to put some data into the form before post, there is no way to do this currently. I think we need add a new event to trigger before the data being sent to the submit function.

The only way to add some data before the post is using iron-ajax element outside of iron-form, so iron-form will turn useless maybe?

**Comment by klarkc** [comment] 2015-07-14 19:36
Workaround:

Create hidden input elements and set the value using Polymer properties initialization:
```html
<form is="iron-form" id="form" method="post" action="{{apiUrl}}">
<input type="hidden" name="foo" value="{{fooValue}}"/>
</form>
<script>
Polymer({
   is: "my-element"
   properties: {
      fooValue: {
          type: String,
          value: "bar"
      }
   }
});
</script>
```

**Comment by zmoshansky** [comment] 2015-07-15 00:51
I was thinking more like inserting the following before [this._requestBot.generateRequest();](https://github.com/PolymerElements/iron-form/blob/master/iron-form.html#L147)
```
if(this._preRequestCallback) {
  this._preRequestCallback(this); 
}
```
or perhaps 
```
this.fire('iron-form-pre-submit', this);
````

**Comment by rnicholus** [comment] 2015-07-22 14:51
Looks like there's a lot of reinventing the wheel going on here. You can hook into the "submit" process and massage the data any way you want already with [ajax-form](https://github.com/rnicholus/ajax-form). 

From the [ajax-form docs](http://ajax-form.raynicholus.com/components/ajax-form/):

>Modifying the data to be submitted

>You have an opportunity to do this by registering a "submitting" event handler. All data in the form, parsed into a JavaScript object (keys = field names, values = field values) will be included on the event's detail.formData property. You can modify formData however you wish. Your changes will represent the actual data submitted to your endpoint. Note that files, if applicable, will be included in this object as well!

**Comment by eximius313** [comment] 2015-08-08 19:40
+1 for this feature

@rnicholus Yes, version  1.6.0 of ajax-form worked great, but with 2.0 (which is unfortunately the only version compatibile with Polymer 1.0) you cannot submit TinyMce editor anymore (https://github.com/rnicholus/ajax-form/issues/67).
Also your file-input (which was another reason to stick with ajax-form) is not supporting Polymer 1.0 and as you have said in one of my bug requests - you don't have much time lately to do that, so we must search for other options :(

**Comment by rnicholus** [comment] 2015-08-08 19:42
The current version of Ajax-form works fine with any version of polymer. In
fact, I pulled out the dependency a while back, so it works fine with or
without polymer.

**Comment by eximius313** [comment] 2015-08-08 19:53
But still it doesn't support polymer input elements and there is no hope that it will. The same with TinyMCE which just stopped working in 2.0.

**Comment by rnicholus** [comment] 2015-08-08 19:55
Sure it does. It always has to my knowledge. File an issue if you have some
specific knowledge that I am unaware of.

**Comment by eximius313** [comment] 2015-08-08 19:59
I have already done it.
https://github.com/rnicholus/ajax-form/issues/67
https://github.com/rnicholus/ajax-form/issues/63
I just couldn't provide "public link" :(

**Comment by rnicholus** [comment] 2015-08-08 20:13
The tinymce issue is a bit out of scope, and the other reported issue
cannot be verified. I asked the reporter for specific information required
to reproduce. That thread has been silent for a while, and I am unable to
reproduce, so I don't believe it exists anymore.

Again, I'm not aware of any specific issues that prevent Ajax-form from
being using alongside polymer. In fact, Ajax-form is by far the most
complete and flexible extension of the html form element available, thanks
to the power of the web components spec.

Let's take any further discussion into an appropriate forum, such as an
issue in the Ajax-form repo.

**Comment by indolering** [comment] 2015-12-15 20:38
Can we close this ticket?

**Comment by notwaldorf** [comment] 2015-12-15 20:46
Done!

**Closed by notwaldorf** 2015-12-15 20:46 UTC
Labels: started
