### ISSUE TITLE
Form reset leaves class="checked" on paper-checkboxes

### ISSUE THREAD

**Issue by dman777** [PolymerElements/iron-form#255] opened 2018-03-01 16:27 UTC
### Description
`form.reset` clears paper-checkboxes that are checked, but leaves `class=checked` 

### Expected outcome
checkbox should not have the styling of checked after form submit

### Actual outcome
A checkbox that was checked is unchecked but  the styling of checked remains after form submit
 

### Steps to reproduce

Have a form and have a child element of a form with checkboxes. submit  the form and call form.reset().

### Browsers Affected

- [ X] Chrome

Polymer 1.11.2
iron-form 1.1.5
paper-checkbox -1.4.2

**Comment by notwaldorf** [comment] 2018-03-07 19:10
Closing, as this doesn't have any repro steps; please re-open with a code snippet or a JSBin that actually shows the issue.

I also can't reproduce this in the demo: https://raw-dot-custom-elements.appspot.com/PolymerElements/iron-form/v1.1.6/iron-form/demo/index.html. The first `iron-form` has a `paper-checkbox`, and if you check it and then reset the form, it stays unchecked.

Are you importing `paper-checkbox/paper-checkbox.html` correctly in your code? Is something else throwing errors?

**Closed by notwaldorf** 2018-03-07 19:10 UTC

**Comment by dman777** [comment] 2018-03-17 01:52
Sorry, I can't give a example.... the code base is really complex with forms. Basically, a form with a slotted component among other stuff going on.  

No errors in console. 

Yes, I made sure...paper checkboxes are working all the way except for the reset issue. 

Thanks for trying to reproduce.
